baseURL = ""
languageCode = "en-us"
title = "噗嗤！收藏集！"
theme = "tickets"
paginate = 18
enableRobotsTXT = true

[taxonomies]
  theater = "theaters"

[params]
  description = "The ongoing movie ticket collection of Winston MAO, started in 2018."
  images = ["images/tickets-social.jpg"]
  subTitle = "A Movie Ticket Collection"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "All Tickets"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    identifier = "theaters"
    name = "Theaters"
    pageRef = "/theaters/"
    weight = 2
